### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml.io#10]
I think there would better be a LICENSE file same with `toml-lang/toml`, at least in `specs` folder. If not, no one can use the whole translation docs in the futhur, because the default copyright belongs to all translators self.

**Comment by pradyunsg** [comment]
Indeed! Thanks for flagging this @LongTengDao! ^>^

I do agree that *at least* the `specs/` needs to have the same LICENSE as the original repository.

@cannikin You wrote the bulk of this repository's source code (everything other than the specs/ directory). How do you think we should license those?

**Comment by cannikin** [comment]
Oh boy, the license stuff goes into legal territory and I'm not comfortable recommending anything in that area! That being said, if the original spec is MIT, then it makes sense that all translations are also MIT? Can you just put one in the parent `specs` directory and then covers all the translations automatically?

**Comment by pradyunsg** [comment]
Yes, that sounds like how we should be handling the specs/ directory. What about the rest of the codebase though? :P

**Comment by cannikin** [comment]
If everyone is cool with MIT I can just slap one in there. How does the copyright work? Should it be Tom's name in there?

**Comment by LongTengDao** [comment]
I think toml.io's site files (layout, color scheme, etc.) should not be used by other individuals or organizations without authorization, because there should be only one official website.

I'm not sure who would better be the copyright name of site files (exclude spec files), but it should be the site files' license's primary purpose to always allow and only allow official use.

**Comment by Genarito** [comment]
Is there any update on this? I was openning an issue to ask if I could use some code of this repo to make a site but I realised that there's no license. Have you considered to add a `LICENSE` file to the repo?
