### ISSUE TITLE
Add release dates to files

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml.io#12]
Nowhere in the different versions of the spec published on toml.io it's visible at which date that version was tagged and published. To document TOML's history, it would be good a show a little note "Published on xx April 2020" somewhere at the top or bottom of each version of the spec.

**Comment by cannikin** [comment]
Looks like we could get release dates from tags: https://github.com/toml-lang/toml/releases

**Comment by pradyunsg** [comment]
For backfilling, yea. For the rest, it'll be easy enough to add it to the automation we have
