### ISSUE TITLE
Doubt: Space within the table key

### ISSUE THREAD

**Issue by ju-sh** [toml-lang/toml.io#16]
I had a doubt. Wasn't sure which would be the right place to ask.

From the website, I see that.

`[ g .  h  . i ]` is same as `[g.h.i]`.

But how will 

`[ g h  . i ]` be parsed.

Will `g h` be considered as the first part of the key (not sure if I'm using the right terms (-: )?

Or is it an error?

And in table arrays, are white spaces allowed between the double braces. Is something like `[ [ product]]` valid?

**Comment by cannikin** [comment]
I think this should go in the spec repo since it involves the spec itself: https://github.com/toml-lang/toml

**Comment by eksortso** [comment]
@cannikin I agree, though the answers to @ju-sh's questions are simple.

**Comment by pradyunsg** [comment]
@cannikin we should add an issue template and add this information into the README.

Basically, a better phrasing of "please file issues and questions related to the TOML specification at [link]. This repository/issue tracker is only for the toml.io website and not for the language specification."
