### ISSUE TITLE
Where does the supporting ANBF go?

### ISSUE THREAD

**Issue by pradyunsg** [toml-lang/toml.io#19]
The TOML .md file also has a supporting .abnf file which together serve as the overall specification.

Right now, I don't think we have the .abnf file in any specific location in this repository. @cannikin Any suggestions on how/where to put this on the website + this repository?

**Comment by cannikin** [comment]
Hmm, maybe update the "Text Version" link to be two separate ones, "Text | ABNF"?

**Comment by cannikin** [comment]
Or you mean physically where does that file live? Feels like it's part of the core spec and should probably live in the actual TOML repo. And link to the raw text GitHub link from the website?

**Comment by pradyunsg** [comment]
It's a supporting file along with the .md file. Basically, a specific version of TOML is described by both the .abnf file as well as the .md file.

In other words, TOML 1.0.0 would be described by `toml-v1.0.0.md` and `toml-v1.0.0.abnf`, where the .md file may be translated to multiple languages, and the ABNF won't.

**Comment by cannikin** [comment]
Do you think people will want to view the APNF as a regular thing, within the browser when going to the website? Or is it more of an implementation detail for maintainers and those that are curious? If it's the later I'd just keep it in just the spec repo.

**Comment by pradyunsg** [comment]
I think it's the latter for sure -- it's toward implementing TOML (+ curious cats). OTOH, I really do think it should be versioned w/ the markdown.

**Comment by cannikin** [comment]
Can we just drop it and previous versions into the `specs/en` directory and be good to go? Do we need a mention of it on the website? If anything it seems like the "Get Involved" section at the end of the spec itself could reference it...

**Comment by pradyunsg** [comment]
> Can we just drop it and previous versions into the specs/en directory and be good to go? 

I think we don't need to include the previous versions even.

> If anything it seems like the "Get Involved" section at the end of the spec itself could reference it...

Hmm... we *can* do that. I like this idea so much more than whatever I came up with. :)

**Comment by pradyunsg** [comment]
Alrighty, we dropped the get involved section, but I still think linking to it from the text specification works well!
