### ISSUE TITLE
Mixed-type arrays are still invalid, aren't they?

### ISSUE THREAD

**Issue by eksortso** [toml-lang/toml.io#3]
The example at the top of the page has the following two lines:
```toml
[clients]
data = [ ["delta", "phi"], 3.14159 ]
```

The problem is the value of `data`. which is a mixed-type array, which is invalid in TOML v0.5.0. Although there's an open [issue](https://github.com/toml-lang/toml/issues/553) regarding whether mixed-type arrays ought to be allowed, that issue is tagged _post-1.0_.

So assuming the issue isn't pressed before v1.0.0, do you think we need to remove or replace the mixed-type array from the lead example?

**Comment by cannikin** [comment]
I got it from this example in the README but tried to shorten it to fit the width of an iPhone X:

```[clients]
data = [ ["gamma", "delta"], [1, 2] ]```

If I just wrap my `3.14` in an array would we be good to go?

**Comment by eksortso** [comment]
That'd definitely do it. Array of arrays.

**Comment by pradyunsg** [comment]
Yea. Let's go with array of arrays here. The updated example above seems fine to me.

I'm gonna eagerly close this issue, since we have a resolution.
