### ISSUE TITLE
Internal links (crossrefs) in specs are broken

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml.io#32]
When I click on https://toml.io/en/v1.0.0 on any of the internal links, e.g. in the list of types following "Values must have one of the following types", nothing happens because the link is broken. The problem is that these internal links are tailored for GitHub, but on toml.io the files are rendered in a different way and so the links don't work. For example, "String" is a broken link to https://toml.io/en/v1.0.0#user-content-string, while the correct link would be https://toml.io/en/v1.0.0#string.

toml.io must adjust these internal links when rending the files, to make them work.

**Comment by cannikin** [comment]
Ahh, same issue as this one: https://github.com/toml-lang/toml.io/issues/29 Easy fix, and we talked about adding a build step that'll be sure to remove these if present. Fixing in a moment!
