### ISSUE TITLE
Clarification on normalizing newlines in a string literal

### ISSUE THREAD

**Issue by TonalidadeHidrica** [toml-lang/toml.io#76]
The toml language states:

> TOML parsers should feel free to normalize newline to whatever makes sense for their platform.

I am not sure how to interpret "should feel free".  Is it obligatory to interpret the newline according to what platform the parser is running on, or is it allowed to be parser-dependent on how to interpret newlines in a stirng literal?

**Comment by arp242** [comment]
It's parser-dependent; you *can* change the newlines from `\n` ↔ `\r\n` if you think that makes sense, but you don't need to.

(For my parser I just leave them alone, e.g. if you put a `\r\n` in the file you will always get a `\r\n` out and if you put a `\n` in there you always get a `\n` out; auto-changing newlines always confuses me, but some people seem to like it).

**Comment by TonalidadeHidrica** [comment]
Thanks for the clarification!
